
library(ggplot2)
library(wesanderson)
library(DescTools)
library(PropCIs)
library(RColorBrewer)
library(gridExtra)
library(scales)
library(truncnorm)
library(xtable)
library(reshape2)
library(tidyverse)
library(readxl)
library(knitr)
library(plyr)
library(coin)
library(magrittr)
library(dplyr)
library(ggplotify)
library(grid)
library(ggforce)
library(cowplot)
library(tools)
library(ggrepel)


